development: 
  adapter: postgresql
  database: app_dev
  encoding: utf8
  host: localhost
  username: palmweaver
  password: leewest1
 


production:  
  adapter: postgresql
  url: <%= ENV['postgresql://db_qcs:f1b3bf57c9d6dd27c38f4f3a57a961595f7a7cc88d72406f87002aa2f9eb79c3@postgres:5432/db_qcs'] %> #This is the environment variable created by our Dokku command earlier
  encoding: unicode
  pool: 5