development: 
  adapter: postgresql
  database: app_dev
  encoding: utf8
  host: localhost
  username: palmweaver
  password: leewest1
 


production:  
  adapter: postgresql
  url: <%= ENV['postgresql://db_app:d45ea42fe93f718f20bdb8872d6d1661fa1fd6611425ed8bb9acc7f06b58e61f@postgres:5432/db_app'] %> #This is the environment variable created by our Dokku command earlier
  encoding: unicode
  pool: 5